DROP TABLE IF EXISTS VENUE CASCADE;

DROP TABLE IF EXISTS VENUE_CODE_TEMPLATE CASCADE;

DROP TABLE IF EXISTS VENUE_CODE CASCADE;

DROP TABLE IF EXISTS VISIT CASCADE;

DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS VENUE_USER CASCADE;

DROP TABLE IF EXISTS SETTINGS CASCADE;